# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.1.1
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - sonarcloud/scan
workflows:
  example-workflow:
    jobs:
      - example-job